/* !!!!!!!! AUTOGENERATED !!!!!!! - do not modify the content of this file */
using LetsGetChecked.Event;
namespace MT.Contracts.Events.Order
{
   public partial class OrderCreated  : IVersionedIntegrationEvent {}
}